[theme]
base = "light"
primaryColor = "#B97343"
backgroundColor = "#fbf9f8"
secondaryBackgroundColor = "#f5f3f3"
textColor = "#1b1c1c"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
